### ISSUE TITLE
Parse Bonus

### ISSUE THREAD

**Issue by marianaobmorais** [marianaobmorais/minishell#21]
- [x] Review syntax to accommodate && and ||
- [x] Review syntax to accommodate (   )
- [x] Add types AND && and OR || to t_type structure 
- [x] Add parentheses to t_type structure
- [x] Adapt token_list to consider && and ||
- [x] Adapt token_list to consider ( and )
- [x] Update ft_free_tree
- [x] Change t_exec->args from char ** to t_list ** 
- [x] Change t_redir->target from char * to t_list **
- [x] Change ft_add_args to return t_list ** instead of char **
- [x] Rethink ft_build_tree to consider new types && and ||
- [x] Rethink ft_build_tree to consider (   )

**Comment by joseevilasio** [comment]
```
"if (ft_strchr(INVALIDCHARS, trim[i]))
	{
		ft_stderror(FALSE, "syntax error near unexpected token `%c'", trim[i]);
		ft_exit_status(2, TRUE, FALSE);
		return (-1); //ft_error_handler();
	}"
```
